receivers:
    otlp:
        protocols:
            grpc:
            http:
    prometheus:
        config:
            scrape_configs:
                - job_name: 'otel-collector'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['0.0.0.0:8888']
    hostmetrics:
        scrapers:
            cpu:
            disk:
            load:
            filesystem:
            memory:
            network:
            paging:
            process:
            processes:

exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"
    logging:
        loglevel: debug
    otlp:
        endpoint: ingest.lightstep.com:443
        headers: 
            "lightstep-access-token": "<ACCESS TOKEN>"

processors:
    batch:

service:
    telemetry:
        metrics:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [logging, otlp]
            processors: [batch]
        metrics:
            receivers: [prometheus, hostmetrics]
            processors: [batch]
            exporters: [logging, otlp]