receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318
    prometheus:
        config:
            scrape_configs:
                - job_name: 'dapr'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['nodeapp:9091', 'pythonapp:9092', 'audit-service:9091', 'airflow-trigger-service:9095', 'airflow-config-service:9099', 'management-service:9103', 'lineage-service:9107']
    zipkin:
        endpoint: 0.0.0.0:9411

processors:
    batch: {}

exporters:
    logging:
        loglevel: debug
    prometheus:
        endpoint: "0.0.0.0:8890"
    otlp:
        endpoint: "otel-collector:4317"
        tls:
            insecure: true

service:
    pipelines:
        metrics:
            receivers: [otlp, prometheus]
            processors: [batch]
            exporters: [prometheus, logging]
        traces:
            receivers: [otlp, zipkin]
            processors: [batch]
            exporters: [logging, otlp]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]