receivers:
    otlp:
        protocols:
            grpc:
            http:
    prometheus:
        config:
            scrape_configs:
                # - job_name: 'otel-collector'
                #   scrape_interval: 5s
                #   static_configs:
                #     - targets: ['0.0.0.0:8890']  # Changed from 8889 to 8890
                - job_name: 'dapr'
                  scrape_interval: 5s
                  static_configs:
                    - targets: ['nodeapp:9091', 'pythonapp:9092']
    zipkin:
        endpoint: 0.0.0.0:9411

processors:
    batch: {}

exporters:
    logging:
        loglevel: debug
    prometheus:
        endpoint: "0.0.0.0:8890"  # Changed from 8889 to 8890
    otlp:
        endpoint: "otel-collector:4317"
        tls:
            insecure: true

service:
    # telemetry:
        # metrics:
        #     address: ":8890"  # Changed from 8889 to 8890
    pipelines:
        metrics:
            receivers: [otlp, prometheus]
            processors: [batch]
            exporters: [prometheus, logging]
        traces:
            receivers: [otlp, zipkin]
            processors: [batch]
            exporters: [logging, otlp]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]